name: "CI"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        os: [self-hosted, macos-14]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: nixci
