name: "CI"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  nix:
    runs-on: self-hosted
    strategy:
      matrix:
        system: [aarch64-linux, aarch64-darwin]
    steps:
      - uses: actions/checkout@v4
      - run: |
          # My self hosted runner is ARM
          nix run nixpkgs#sd 'nixpkgs.hostPlatform = "x86_64-linux"' 'nixpkgs.hostPlatform = "aarch64-linux"' ./examples/*/flake.nix
          
          nixci --build-systems "github:nix-systems/${{ matrix.system }}"
