name: "CI"
on:
  push:
    branches:
      - '*'
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v22
        with:
          # We use newer Nix for:
          # - https://github.com/NixOS/nix/issues/7263
          # - https://github.com/NixOS/nix/issues/7026
          nix_version: 2.14.1
          nix_conf: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build example
        id: example
        run: |
          pushd ./examples/both
          # Github Action runners do not support M1 yet.
          nix run nixpkgs#sd mkARMMacosSystem mkIntelMacosSystem flake.nix
          ./test.sh
          popd

          pushd ./examples/linux
          ./test.sh
          popd

          pushd ./examples/macos
          # Github Action runners do not support M1 yet.
          nix run nixpkgs#sd mkARMMacosSystem mkIntelMacosSystem flake.nix
          ./test.sh
          popd
