name: "CI"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  tests:
    strategy:
      matrix:
        os: [self-hosted, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          # Github Action runners do not support M1 yet.
          nix run nixpkgs#sd 'nixpkgs.hostPlatform = "aarch64-darwin"' 'nixpkgs.hostPlatform = "x86_64-darwin"' ./examples/*/flake.nix

          nixci

