name: "CI"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        os: [self-hosted, macos-14]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          # My self hosted runner is ARM
          nix run nixpkgs#sd 'nixpkgs.hostPlatform = "x86_64-linux"' 'nixpkgs.hostPlatform = "aarch64-linux"' ./examples/*/flake.nix
          nixci
